wordpressUsername: helm-user
wordpressPassword: my-password
wordpressEmail: crupib@gmail.com
wordpressFirstName: Helm_is
wordpressLastName: Fun
wordpressBlogName: Learn Helm!
service:
  type: NodePort
replicaCount: 2
resources:
  requests:
    memory: 256Mi
    cpu: 100m
